server:
  port: 8012
#  servlet:
#    context-path: /timesheet
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timesheetproject
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: timesheet027@gmail.com
    password: gsmeastctdspyesu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    enabled: true
    prefix:classpath: /resources/
    suffix: .html
Timesheet:
  baseURL: http://timesheet.com/activation
  baseURLEmployees: http://timesheet.com/activation/Employees
  baseURLForgotPassword: http://timesheet.com/forgot-password
  from:
    email: timesheet027@gmail.com
#spring-doc:
#  group-configs:
#    - group: com.timesheet
#      packagesToScan:
#        - "com.timesheet.module"
#  swagger-ui:
#    path: /timesheet-swagger-ui.html
#  api-docs:
#    path: /v3/timesheet-api-docs

